### ISSUE TITLE
There is no min/max commit message line length of the title

### ISSUE THREAD

**Issue by storenth** [compilerla/conventional-pre-commit#69]
Standard way am doing using hook like that:
<img width="1132" alt="Screenshot 2023-11-09 at 21 16 37" src="https://github.com/compilerla/conventional-pre-commit/assets/18244131/bf04aff3-0b03-4ced-a6d7-a8676d108882">

**Comment by thekaveman** [comment]
Thanks @storenth for the question.

Since this hook is focused on Conventional Commits, and [the spec](https://www.conventionalcommits.org/en/v1.0.0/#specification) makes no mention of commit message length other than `"short"`

> The description is a short summary of the code changes

And `"longer"`

> A longer commit body...

I'm less inclined to expand the scope of the hook into length checking. 

There are other hook systems out there like [Husky](https://typicode.github.io/husky/) that are more expansive and maybe more appropriate for your use-case.
